---
# Our Netflow configuration does not depend on any Netflow-specific vars YAML.
# Everything is hard-coded into the jinja2 template.
# But we do need the layer-3 definitions, since we'll be configuring Netflow
# on the layer 3 interfaces.
- include_vars:
    file: '06-layer-3-vars.yml'

- name: Netflow
  template: src=netflow_configurations.j2 dest={{ cfg_dest }}
  with_items:
    "{{ devices }}"
    
