---
- include_vars:
    file: '08-qos-vars.yml'
    
- include_vars:
    file: '06-layer-3-vars.yml'
    
- include_vars:
    file: '05-layer-2-vars.yml'
    
- name: QoS
  template: src=qos_configurations.j2 dest={{ cfg_dest }}
  with_items:
    "{{ devices }}"
    
